name: finance_app
description: Personal Finance Tracker
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.18.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # UI & Fonts
  cupertino_icons: ^1.0.2
  google_fonts: ^6.1.0

  # State management
  flutter_riverpod: ^2.3.6

  # Database
  drift: ^2.7.0
  drift_sqflite: ^2.1.0
  path_provider: ^2.0.14

  # Charts
  fl_chart: ^0.65.0

  # Utils
  intl: ^0.17.0
  uuid: ^3.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.6
  drift_dev: ^2.7.0
