name: finance_app
description: Personal Finance Tracker
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.18.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # UI & Fonts
  cupertino_icons: ^1.0.2
  google_fonts: ^6.1.0

  # State management
  flutter_riverpod: ^3.0.3

  # Database
  drift: ^2.7.0
  drift_sqflite: ^2.0.1
  path_provider: ^2.0.14

  # Charts
  fl_chart: ^1.1.1

  # Utils
  intl: ^0.20.2
  uuid: ^4.5.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.6
  drift_dev: ^2.7.0
